A) DESC TABLE_NAME;
B) SELECT * FROM TABLE_NAME;
SELECT NAME, DEPT_NAME FROM INSTRUCTOR;
SELECT NAME, SALARY FROM INSTRUCTOR WHERE DEPT_NAME = 'Comp. Sci.';
SELECT * FROM INSTRUCTOR WHERE DEPT_NAME = 'Physics' and SALARY <
'90000';
SELECT NAME FROM INSTRUCTOR WHERE DEPT_NAME != 'Comp. Sci.';
G) SELECT DISTINCT DEPT_NAME FROM INSTRUCTOR;
H) SELECT COURSE_ID FROM TEACHES WHERE SEMESTER = 'Spring' and YEAR
= '2009';
I) SELECT TITLE FROM COURSE WHERE DEPT_NAME ='Comp. Sci.' and
CREDITS!= 3;
J) SELECT * FROM COURSE ORDER BY DEPT_NAME DESC;
K) ALTER TABLE INSTRUCTOR ADD DATE_OF_JOIN DATE;
L) UPDATE INSTRUCTOR SET DATE_OF_JOIN=TO_DATE('2022-05-22', 'YYYY-
MM-DD'); -- WHERE <YOU CAN CHANGE VALUES FOR SPECIFIC ROWS>
M) ALTER TABLE INSTRUCTOR RENAME COLUMN DEPT_NAME TO DEPARTMENT;
   ALTER TABLE COURSE RENAME COLUMN DEPT_NAME TO DEPARTMENT;
   ALTER TABLE DEPARTMENT COLUMN DEPT_NAME TO DEPARTMENT;
N) ALTER TABLE PREREQ RENAME TO PREREQUIRED;
O) ALTER TABLE COURSE RENAME COLUMN COURSE_ID TO SUB_CODE;
P) ALTER TABLE INSTRUCTOR MODIFY NAME VARCHAR(50);
Q) ALTER TABLE INSTRUCTOR RENAME TO FACULTY_INFO;
R) ALTER TABLE COURSE MODIFY COURSE_ID VARCHAR(8);
S) DROP TABLE PREREQUIRED;
ALTER TABLE DEPARTMENT RENAME COLUMN BUILDING TO BUILDER;
